services:
  swarakaka_inertia.inertia:
    class: SwaraKaka\InertiaBundle\Service\InertiaService
    public: false
    arguments:
      $engine: '@twig'
      $requestStack: '@request_stack'
      $container: '@service_container'
      $serializer: '@serializer'

  SwaraKaka\InertiaBundle\Architecture\InertiaInterface: '@swarakaka_inertia.inertia'

  swarakaka_inertia.inertia_error_response:
    class: SwaraKaka\InertiaBundle\Architecture\DefaultInertiaErrorResponse
    public: false

  swarakaka_inertia.gateway:
    class: SwaraKaka\InertiaBundle\Ssr\HttpGateway
    arguments:
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
      $inertia: '@swarakaka_inertia.inertia'

  SwaraKaka\InertiaBundle\Architecture\GatewayInterface: '@swarakaka_inertia.gateway'

  swarakaka_inertia.twig_extension:
    class: SwaraKaka\InertiaBundle\Twig\InertiaTwigExtension
    public: false
    arguments:
      $inertia: '@swarakaka_inertia.inertia'
      $gateway: '@swarakaka_inertia.gateway'
    tags:
      - { name: twig.extension }

  SwaraKaka\InertiaBundle\EventListener\InertiaListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }
      - { name: kernel.event_listener, event: kernel.response }
    arguments:
      $inertia: '@swarakaka_inertia.inertia'
      $csrfTokenManager: '@security.csrf.token_manager'
      $debug: '%kernel.debug%'
      $container: '@service_container'
      $defaultInertiaErrorResponse: '@swarakaka_inertia.inertia_error_response'

  SwaraKaka\InertiaBundle\EventListener\InertiaResponseAttributeListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view }
    arguments:
      $inertia: '@swarakaka_inertia.inertia'
